### ISSUE TITLE
Please update Readme.md (vital info is missing)

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#1]
Hi and thanks for this wonderful plugin @ata4

I was just about to post earlier an issue that seemed to break many games with graphical issues and gave exceptions until it struck me that you have to use [cxd4's RSP](https://github.com/cxd4/rsp) for Angrylion, this fork included.

To avoid future issue reports that would have been similar to the one I was about to create, could you update the Readme.md to reflect this.

cxd4 haven't got any releases but this is a precompiled RSP plugin (which I have attached) that works perfectly with your fork of Angrylion and it's relatively new from this summer.

You could attach it to the Readme.md to if you want.

[cxd4 rsp.zip](https://github.com/ata4/angrylion-rdp-plus/files/1262589/cxd4.rsp.zip)

**Comment by theboy181** [comment]
@SigmaVirus can you explain what games? I use zilmars RSP (cause its faster) in LLE mode.

**Comment by SigmaVirus** [comment]
With Zilmar's RSP I get numerous exceptions like these:

> Exception caught. File: D:\My Programs\Emulation\Project64\Source\Project64\N64 System\C Core\C Core Interface.cpp. Line: 355

Games affected by this exception for me is:
Legend of Zelda, The - Majora's Mask (Europe)
Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube Edition)
Legend of Zelda, The - Ocarina of Time (Europe)
Paper Mario (Europe)
Perfect Dark (Europe)
Super Smash Bros. (Europe)

Yoshi's Story (Europe) and especially the Jungle Puddle level have severe graphical glitches with Zilmar's RSP

Games not playable, severe graphical glitches I just can't have it like that.

As a reference, with the ParaLLEl RetroArch core you have to use the cxd4 RSP enable to use Angrylion, and when I used cxd4's RSP in Project64 every issue I had was gone and I could play the games perfectly.

**Comment by theboy181** [comment]
@SigmaVirus I cant say I have test many PAL games, I will have to look into that. Is it possible you open an issue on git for PJ64 if that is the case? Just make sure you are using latest builds. I know that some issues, an optimizations have been added to it.

**Comment by SigmaVirus** [comment]
Sure, I'll have a look at it tomorrow and if it's still issues with newer Project64 builds and Zilmar's RSP I'll make sure to file an issue for it.

**Comment by SigmaVirus** [comment]
OK, seems you're right @theboy181 because the latest Project64 builds works with Zilmar's RSP, however those builds had their own share of separate issues and I had numerous crashes attempting to End Emulation with F12.

I guess if you're reasonably up to date with Project64 there is no need for cxd4's RSP like in my case as I'm still using Project64 1.7.0.50 rev23 (it's a stable and solid release and I'm glad I have kept it all these years)

OK so to sum it up:
1. If you're using older builds you have to use cxd4's RSP to avoid exceptions and graphical glitches
2. If you're on newer builds cxd4 is not needed and angrylion-rdp-plus works with Zilmar's RSP

I'll close this issue now.

**Comment by SigmaVirus** [comment]
@ata4, @theboy181 

I recently discovered that you can use a newer version of Zilmar's RSP in Project64 1.7 and it works PERFECTLY!
Great performance too without having to change emulator.

I have always had trouble with Project64 2.x versions, it's an unstable mess with crashes right from the get go and it's still happening today.

On Project64 1.7 I have to do something really stupid and serious to make it crash.

This particular RSP works very well with Project64 1.7
[RSP 1.7.1.9999.zip](https://github.com/ata4/angrylion-rdp-plus/files/1272020/RSP.1.7.1.9999.zip)
