### ISSUE TITLE
StarCraft 64

### ISSUE THREAD

**Issue by Zimond47** [ata4/angrylion-rdp-plus#102]
Hi there. 
In StarCraft 64 you get a lot of horizontal corrupted lines on the screen which flicker rapidly (like a bad VHS playback) This only happens when Mutlicore is enabled (i used Project64) and this effect can be altered with the compatibility option (slow = only a few lines at the bottom, fast = almost on the whole screen) 

Without Multicore it looks fine but  menues and fmvs are way to slow to enjoy.

Thanks for this great plugin and I hope it's still in developement :)

**Comment by GitMoDu** [comment]
Have you tried Thread-Sync Level = High?
