### ISSUE TITLE
Frame rate drops and skipping audio

### ISSUE THREAD

**Issue by 71knight** [ata4/angrylion-rdp-plus#104]
Guys, angrylion seems to have problems with alpha transparencies, motion blur frame buffer effects and high resolution static graphics.  Pilotwings 64 menu screens, Killer Instinct gold character bio's, legend of the mystical ninja starring goeman intro with robot face motionblur effect, goemon's great adventure underwater scene looking interlaced, shadowgate 64 choppy framerate and audio in the castle.  My specs i7 7700 non K, win10 maxed out power settings on everthing, using mupen64+ next in retroarch with dynamic interpreter, parallel, and angrylion rdp as the plugins.

**Comment by OtavioRaposo** [comment]
You should use HLE RSP. Parallel has some known problems, like game crashing in Indiana Jones, after finishing a level. Maybe it will solve some performance issues for you as well.

**Comment by Jj0YzL5nvJ** [comment]
> Parallel has some known problems, like game crashing in Indiana Jones, after finishing a level.

[That is a know dynarec problem](https://github.com/mupen64plus/mupen64plus-core/issues/572), old dynarec is more "fragile", new dynarec is more "resistant". Interpreter is immune.

**Comment by OtavioRaposo** [comment]
Interpreter is unplayably slow. I can't make dynarec work with this game without having to wait a long time and use aggressive cpu.

**Comment by theboy181** [comment]
If you have an i7700 and it’s not a K, do you have to state it?  Maybe I’m being ignorant when I state I have a KS?
