### ISSUE TITLE
Donkey Kong 64

### ISSUE THREAD

**Issue by GibbyShadows** [ata4/angrylion-rdp-plus#107]
An interesting error has appeared when starting up DK64. When it starts, all is normal after the nintendo screen, and the "OK" sound. After that, the sound remains normal, but the intro is sped up to 5 times it's normal speed, and then Project64 crashes (specifically after the rare symbol is shown) due to a fatal error. This is interesting, as no other game has exhibited this error in the slightest, and games like Crusin World actually run better (and that cut off from the Nintendo logo is gone, finally!).

To specify, this is what I had running with Project 64

Video plugin: angrylion RDP Plus r8
Audio Plugin: Azimer's AUdio v0.07 WIP 10
Input Plugin: N-RAGE for PJ64 2.5.3
RSP: 1.7.4 

Graphics HLE and Audio HLE were off during this, as RDP Plus requires it.

**Comment by CrashOveride95** [comment]
Is this a nightly build of Project 64?

**Comment by GibbyShadows** [comment]
I do not think it is, no. This is Project 64 2.4.0 according to the file

**Comment by LegendOfDragoon** [comment]
Unfortunately thats an issue with Project64. It doesn't work well with LLE graphics in some games made by Rare. Try using GLideN64 with LLE to see if you have the same issue with the speed of the game.

**Comment by GibbyShadows** [comment]
After some trial, it turned out to be the video plugin. It's unfortunate that rare games are affected by this, but thanks for helping out!

**Comment by Alexn64gamer0712** [comment]
is there any progress you can tell us about rare games not working on LLE? thanks in advance
