### ISSUE TITLE
Change Internal Resolution?

### ISSUE THREAD

**Issue by modernretrocoder** [ata4/angrylion-rdp-plus#108]
Is it possible, using this plugin, to change the Internal Resolution to a multiple of the original N64 resolution or to the same as the output resolution? I'd like to play a game rendered at 1080p like with GlideN64 but still with the Unfiltered Output Mode, Nearest-neighbor Interpolation and closer accuracy of RDP Plus. Is this or will this be implemented in any capacity?

**Comment by CrashOveride95** [comment]
tbh I'm pretty sure thats outside the scope of the project, closest thing is Parallel-RDP in retroarch

**Comment by modernretrocoder** [comment]
Can ParaLLEl-RDP be used with Project64 instead of RetroArch?

**Comment by CrashOveride95** [comment]
No one has ported it yet, so no

**Comment by modernretrocoder** [comment]
Looks like I'll have to get used to Retroarch then, thanks for your help. I'll keep the issue open in hopes that ata4 will clarify if this change will be implemented before closing.

**Comment by ata4** [comment]
Changing the internal resolution is something I've experimented with, but I didn't have much success. While it's certainly possible somehow, the performance of a software renderer would be absolutely abyssal, unlike Parallel using Vulkan. I'd expect no more than 1 FPS with a 4x rendering resolution. 2x/3x is maybe possible with a beefy CPU.

**Comment by modernretrocoder** [comment]
Are you aware of any other video plugins for Project64 which have an Unfiltered Output Mode, Nearest-neighbor Interpolation and Higher Internal Resolution? ParaLLEl RDP seems to be exactly what I'm looking for but I hate that I have to go through RetroArch to use it, if it had a Project64 port it would be my go-to graphics plugin without a doubt, but I'm really not looking for pixel-perfect software rendering accuracy, just a fulfillment of those 3 aforementioned criteria, what are your suggestions?

**Comment by CrashOveride95** [comment]
GLideN64?

**Comment by modernretrocoder** [comment]
GlideN64 forces Bilinear Filtering for some godforsaken reason so unfortunately not. :(

**Comment by CristianJLima** [comment]
Your plugin is the only one that solves pokemon snap bugs, without it there is no way to finish the game, congratulations on the work, at the moment only in cutscenes the frames fall below 20, but the feat is impressive after so many years I know the project 64, as soon as possible give us more improvements @ata4

**Comment by Jj0YzL5nvJ** [comment]
> Your plugin is the only one that solves pokemon snap bugs

Yeah?...
https://github.com/gonetz/GLideN64/issues/2046
https://github.com/gonetz/GLideN64/pull/2179
https://github.com/gonetz/GLideN64/issues/2213
