### ISSUE TITLE
Ocarina of Time Drain the water in bottom of the well

### ISSUE THREAD

**Issue by AlexN64gamer** [ata4/angrylion-rdp-plus#114]
When playing song of storms to drain the well in Kakariko theres a cinematic where it rains and the mill drains the water so can enter the well, the cinematic crashes the game (rdp plus 8)

**Comment by oddMLan** [comment]
If you're playing Ocarina randomizer you need to enable protected memory.

**Comment by AlexN64gamer** [comment]
Nop, its a standard PAL version

**Comment by RokkumanX** [comment]
Would you mind sharing your save game?

I completed Ocarina of Time a couple of months ago and didn't experience any crashes, I too own the PAL version of the game.

**Comment by ata4** [comment]
I also can't replicate that crash with r8 or latest, Project 64 2.4 and `Legend of Zelda, The - Ocarina of Time (Europe) (En,Fr,De) (Rev 1).z64`.

**Comment by LegendOfDragoon** [comment]
Alex probably doesn't have protect memory enabled

**Comment by LegendOfDragoon** [comment]
@AlexN64gamer please check to see if you have Protect Memory enabled in Project64 for this game.

**Comment by AlexN64gamer** [comment]
Tested with protect memory enabled, it now works well again, thanks a lot
