### ISSUE TITLE
Black bar bottom of the screen all games (example Goldeneye)

### ISSUE THREAD

**Issue by pitrako** [ata4/angrylion-rdp-plus#116]
I get a black border at the bottom of the screen with project64, hide overscan option does nothing:
![Sin título](https://user-images.githubusercontent.com/42267151/106398501-711fd580-6413-11eb-912e-f6d59091ab4c.png)

**Comment by Jj0YzL5nvJ** [comment]
At least it does more than it does with mupen64plus...
See #75

**Comment by pitrako** [comment]
In m64p (have mupen64plus-video-angrylion-plus) this game and others like perfect dark and majora's mask don't have that black line, but has problems like sound crackling after a minute or less of playing, and some games like xena warrior princess don't boot.
