### ISSUE TITLE
Perfect Dark doesnt work at all with the last release

### ISSUE THREAD

**Issue by AlexN64gamer** [ata4/angrylion-rdp-plus#117]
With 1.6 on Project64 2.3.2, Perfect Dark (either PAL or NTSC) just gives me a black screen at startup, nothing more. im using RSP default plugin (Jabos 1.7) I think the problem is graphics on LLE because when I use GlideN64 4.0 and turn HLE graphics on, the game works just fine, even on Original internal n64 resolution, I also tried Filtered and Unfiltered modes, and make no difference, thanks in advance

**Comment by LegendOfDragoon** [comment]
The problem is PJ64, rather than the video plugin. I think LLE graphics for Perfect Dark works in latest nightly, but has other issues.

**Comment by AlexN64gamer** [comment]
So, should I use Mupen64 instead? will PD work with the last release of that emulator?

**Comment by Jj0YzL5nvJ** [comment]
PJ64:
https://www.pj64-emu.com/nightly-builds

m64p:
https://github.com/loganmc10/m64p/releases

Info & WIPs:
https://github.com/ata4/angrylion-rdp-plus/issues/29#issuecomment-720213711

**Comment by LegendOfDragoon** [comment]
> So, should I use Mupen64 instead? will PD work with the last release of that emulator?

It should work on that

**Comment by AlexN64gamer** [comment]
Ok guys thanks a lot everyone, I tried with the lastest build (Project64) turning "Protect Memory" on and LLE graphics, now it works  :)
