### ISSUE TITLE
Problem with transparencies on trees on surface level

### ISSUE THREAD

**Issue by AlexN64gamer** [ata4/angrylion-rdp-plus#119]
Hi devs, I hope youre all doing well and staying safe : ) I just wanted to point out that theres still that issue in Goldeneye 007, on Surface level when you walk across the plateau next to the pine trees that sorrund it, theres a weird transparency effect that doesnt happen on real hardware, could that be fixed some way?

Thanks in advance.

Alejandro.

**Comment by Jj0YzL5nvJ** [comment]
This? https://imgur.com/a/4qqGrvc

I remember seeing that on real hardware too. Soldiers can even shoot you through it and you can shoot them too.
Maybe my memory is failing, but I think the effect looked darker on real hardware.

**Comment by AlexN64gamer** [comment]
Yes ¡¡ the bug in the pictures is what I mean, but I have tested it on my PAL N64 with a copy of Goldeneye 007 and I havent seen anything like that, maybe the PAL version was fixed or something?
