### ISSUE TITLE
Dual monitor: Error in full screen

### ISSUE THREAD

**Issue by beckno** [ata4/angrylion-rdp-plus#13]
Hi. I use dual monitor in my setup, my vga card ia AMD Radeon 260x. When i go to full screen in PJ64 using Angrylion RDP Plus, the screen has been cuted, Something with fifty percent of the image is shown on each monitor. it appears that the centering is incorrect. Thank you.

**Comment by beckno** [comment]
Something Just Like This:

https://i.imgur.com/dhVdRQB.jpg

**Comment by ata4** [comment]
I'm aware that multi-screen setups aren't supported very well with the current borderless window method. In the photo, it looks like the center would be correct if the screen didn't have borders. I don't have much experience with multiple screens, but I've read somewhere that the driver can compensate this somewhere in the options.

**Comment by SSSTREDDD** [comment]
Im having the same issue. Makes me sad :( This plugin is absolutely amazing but I cannot use it.
