### ISSUE TITLE
[Regression] Invisible Nintendo logo text

### ISSUE THREAD

**Issue by GhostlyDark** [ata4/angrylion-rdp-plus#138]
Ocarina of Time and Majora's Mask are affected.

Nightly https://github.com/ata4/angrylion-rdp-plus/commit/6660e93acc94506933238c9a593494684d0d3bde
![image](https://user-images.githubusercontent.com/31742919/153928147-ad11a81f-50e2-42b4-9910-0a08f22d9035.png)

v1.6 looked normal.

**Comment by ata4** [comment]
Can confirm, I believe it was caused by d95d3aa1bfc2c0812e70258fd9fa66bb5dd183a9. I'll take a look.

**Comment by ata4** [comment]
Finally found the error: it was a missing z_compare call in render_spans_2cycle_complete. I'll check the other functions as well in case there are more regressions.
