### ISSUE TITLE
Expose busyloop option for the Project64 API.

### ISSUE THREAD

**Issue by Fluvian** [ata4/angrylion-rdp-plus#140]
There doesn't seem to be a noticeable performance difference between multithreaded rendering and single threaded rendering when using the "Slow, few glitches" option, the only difference I could find is that the CPU usage is about 8x times higher.

Meaning whether or not I have multithreaded rendering on or off, certain screens where emulation speed dips below 100% will have the exact same performance.

Now I don't know if this behaviour is intended but using this option makes multi-threading essentially redundant.

**CPU Specifications**
Ryzen 7 5800X
8 Cores
16 Threads
3.8GHz Base Clock
4.7GHz Boost Clock

**Comment by Jj0YzL5nvJ** [comment]
Well, **that description** certainly leaves room for misunderstanding. It's useless to **synchronize** a thread with itself.
**Fast** is _async threads_ (`DpCompat` = 0) and **Slow** means _"sync threads"_ (`DpCompat` = 2).

I think the most important part to achieve true synchronization on AMD processors is not exposed in the plugin for Project64, it is only exposed in mupen64plus =P (`BusyLoop`)

https://imgur.com/a/LO46NgT (Watch them in order, the sort is messed)

In any case it's better never to use all available threads.

> First of all there are many myths and misconceptions related to multithreading in general. To that we must add the misunderstandings of how such techniques benefit videogames.
> All this together with the ignorance of some end-users with the firm belief that "the more the better" and/or "the newer the better". When in reality in many cases "less is more and better".
> 
> What am I referring to with all this?
> 
> Multithreading needs to be adjusted in some cases, that's why it keeps getting better.
> Some CPUs can benefit more than others. Too many multithreading could potentially impair performance in some games by spending more time syncing threads.
> Some newer Intel processors don't have hyperthreading and other older processors work better without it... etc.

**Comment by Fluvian** [comment]
Interesting, is there a reason BusyLoop is not exposed on the Project64 API side?

**Comment by Jj0YzL5nvJ** [comment]
> Interesting, is there a reason BusyLoop is not exposed on the Project64 API side?

The author who originally exposed `BusyLoop` in mupen did so just to improve performance on Android. It was a lucky accident, that this also fixed mupen sync on AMD processors. #115 #105
