### ISSUE TITLE
G-sync/Freesync support

### ISSUE THREAD

**Issue by theboy181** [ata4/angrylion-rdp-plus#16]
I just got my new laptop and its 120hz and supports G-sync. I was hoping that you could looking at adding support for the advanced syncing of Nvidia and AMD. 

ATM I have to manually set the monitor to 59hz and turn off the frame limit. The plugin drops a lot of frames for some reason..

3rd world problems, I guess.

**Comment by ata4** [comment]
By adding an option for exclusive fullscreen in 422a7d80dae62c6c1fd5a20a932f129416c4e0b1, both Freesync and Gsync should work now.
