### ISSUE TITLE
Perfect Dark crashes on angrylion's RDP Plus r4 with unfiltered as saved startup value

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#19]
Finally got the chance today to try out the new release and it's looking good so far except that Perfect Dark crashes immediately, something that has not happened before using angrylion's RDP Plus r3 or a compiled version from 2017-09-14 which shows up as "angrylion's RDP Plus r3-85 dirty" in Project64

There has to be something that have changed since 2017-09-14 up till now that have broken Perfect Dark and I have tried both Zilmar's RSP (1.7.1.9999) and cxd4's RSP and it still crashes.

**Comment by ata4** [comment]
I guess this one is also caused by Project64:

https://github.com/project64/project64/issues/1022#issuecomment-326142857

**Comment by SigmaVirus** [comment]
Yes Perfect Dark is known to be problematic with LLE with freezes in Project64 but it works OK if you are patient with the intro.

However Perfect Dark flat out crashes the emulator with the latest angrylion's RDP Plus release (r4) and has nothing to do with the issue you linked to and besides I'm on Project64 1.7.0.50 rev23 from 2010 so that commit from Zilmar is pretty irrelevant for this case.

Something have changed during the last couple of weeks because older versions of the angrylion's RDP Plus plugin works perfectly.

**Comment by loganmc10** [comment]
Yeah I think this might be different, that commit to Project64 actually fixed Perfect Dark, while breaking pretty much every other Rare game in LLE.

**Comment by theboy181** [comment]
I have not had any luck with PD and LLe on PJ ever. :(

**Comment by LegendOfDragoon** [comment]
>Yes Perfect Dark is known to be problematic with LLE with freezes in Project64 but it works OK if you are patient with the intro.

I assume you must be playing the PAL version. Is that correct?

**Comment by loganmc10** [comment]
I just tested this in mupen64plus. I get a crash when vi_mode = 1 (unfiltered), but no crash when vi_mode = 0

**Comment by ata4** [comment]
With most recent PJ64 builds, PD actually seems to work fine, both NTSC and PAL. But it breaks LLE for many other games.

**Comment by SigmaVirus** [comment]
@theboy181
That's strange, it works OK for me.

If you wait to press anything until the Perfect Dark logo starts to loop and the ambient music starts to play it will not freeze in LLE.

@LegendOfDragoon
Yes I'm using the (Europe) version of Perfect Dark.

@ata4
You'd be surprised of what Project64 1.7 can achieve even today

**Comment by SigmaVirus** [comment]
@ata4, @loganmc10 is right it's because of unfiltered.

Let me explain, if you start fresh without a configuration file and start for example Super Mario 64 and then you choose unfiltered instead of the default filtered close the game and the settings is saved.

Then you start Perfect Dark and the game will crash because now unfiltered is the current value.

If you start fresh again without configuration file Perfect Dark will boot up correctly with the default filtered value. However you can change to unfiltered without the game crashing while it's running but if you shut down and restart the game it will crash.

So it's something to do with unfiltered as the selected value indeed.

**Comment by ata4** [comment]
Okay, with that description, I was finally able to reproduce the issue. There was a missing check for a valid `hres` and `vres`, so there were attempts to display frames with negative dimensions. In filtered mode, Angrylion's calculations are more sophisticated and handled that case correctly.

**Comment by ata4** [comment]
Here's also a build with the fix for testing:
[angrylion-plus.zip](https://github.com/ata4/angrylion-rdp-plus/files/1341010/angrylion-plus.zip)

**Comment by SigmaVirus** [comment]
@ata4 THANKS A TON, Perfect Dark works perfectly with unfiltered as selected start output mode!!!
Now we're back in business, YAY!!!
