### ISSUE TITLE
Test results

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#2]
Thought I might post some test results now that I got everything setup properly (which I didn't before thanks to the cxd4 RSP mishap)

This is my current emulation machine:
i7 4790K at stock clock, NVIDIA Strix OC 1060 6GB, 16GB RAM and Windows 10 2016 LTSB

For my tests I have also used Project64 1.7.0.50 rev23 with my custom .rdb which is still holding up today!

**1. 007 - GoldenEye (Europe)**
Works as expected with no major issues, fullspeed most of the time with small occasional drops if there is explosions and smoke on screen

**2. DOOM 64 (Europe)**
Works as expected with no major issues, fullspeed

**3. Legend of Zelda, The - Majora's Mask (Europe)**
Works as expected with no major issues, fullspeed with small occasional drops

**4. Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube Edition)**
Works as expected with no major issues, fullspeed

**5. Legend of Zelda, The - Ocarina of Time (Europe)**
Works as expected with no major issues, fullspeed

**6. Mario Kart 64 (Europe)**
Works as expected with no major issues, fullspeed

**7. Paper Mario (Europe)**
Works as expected with no major issues, fullspeed

**8. Perfect Dark (Europe)**
This game is a little problematic to get going because if you press start too quickly it will freeze at the Perfect Dark logo forcing you to restart, something that does not happen using GLideN64 and the regular RSP (1.7.0.3)

However if you wait patiently for the intro sequence to finish then you can press start and the game proceeds as usual. The game then works as expected, fullspeed with small ocassional drops

**9. Star Wars - Shadows of the Empire (Europe)**
Works as expected with no major issues, fullspeed

**10. Super Mario 64 (Europe)**
Works as expected with no major issues, fullspeed

**11. Super Smash Bros. (Europe)**
Works as expected with no major issues, fullspeed

**12. Yoshi's Story (Europe)**
Works as expected with no major issues, fullspeed

That's all the games I own physically I'm afraid but never the least I was very satisfied with these results, and as you said in a post on Reddit, the project is WIP so it can only get better from here.

To be able to have this experience without worrying about performance that is absolutely outstanding!

**Comment by ata4** [comment]
That sounds pretty good indeed! I have a pretty low-end CPU, so a comparison with a 4790K can help me to estimate how much optimizations are required to make most games run well on an average to high-end system.

The occasional drops are most likely caused by alpha texture rendering, which is a massive bottleneck on most LLE RDP plugins. Not sure yet how to improve the performance there, it's certainly a non-trivial problem.

**Comment by SigmaVirus** [comment]
Well and I have noticed the framerate drops quite significantly when you experience or cause explosions in GoldenEye, damn those smoke clouds afterwards is poison on the speed.

**Comment by petran79** [comment]
I tested Duck Dodgers on the same CPU and utilization would reach 80% while FPS would drop at 55fps.
Castlevania 2 intro video would reach 80% too.

Conker cutscenes did run at 50fps most of the time. In-game runs at 60fps

**Comment by SigmaVirus** [comment]
This was created at the time when I first discovered this plugin and when I initially tested it and we have come a long way since then.

The plugin works more or less perfect these days with newer versions of Zilmar's RSP, both on Project64 1.7 and 2.4

Closing this now, future performance issues and regressions should be filed separately anyway.

**Comment by gamer191** [comment]
I'm pretty sure Perfect Dark (Europe) no longer has that issue, by the way
