### ISSUE TITLE
Aspect Ratio/Stretch Settings Possible?

### ISSUE THREAD

**Issue by Boviligg** [ata4/angrylion-rdp-plus#21]
Hi,
Fantastic work on this plugin!
I'm just wondering if it's possible to implement some sort of stretch to full screen size option? The reason i ask is i'm running a Windows emulation machine hooked up to a 15KHz standard definition CRT TV running at low resolutions. 
When i run this plugin at 320x240 it seems to be squished both vertically and horizontally for some reason, instead of taking advantage of the full screen size as i would expect it should. 
As you can imagine it's causing lots of unwanted artefacts from the image being squeezed.
I understand this is a very niche setup i have, but thought i'd see if it's possible to implement regardless.

Cheers.

**Comment by Krusher97** [comment]
I would like add to this and ask for a general ability to crop the image. A lot of games have overscan and I can't seem to find a way to remove it.

I apologize in advance if something like that is already implemented. I couldn't find anything about it.

**Comment by theboy181** [comment]
I wonder if there is some RAW output mode for OpenGL. then they TV could handle the resolutions. Over scan at this point would be the characteristics of your CRT.

**Comment by ata4** [comment]
I did some experiments to get rid of the overscan and although it appears to work, it's somewhat tricky and requires some code changes to my internal screen API. Also, it will never be possible to eliminate all borders reliably, because some are added by the game itself.

**Comment by theboy181** [comment]
dont break it to fix it :)

**Comment by SigmaVirus** [comment]
@ata4 Any chance of a test build to try this out? Would really like to see if the commit you made helps.

Thanks in advance!

**Comment by LoStraniero91** [comment]
It think overscan removal should be an option, as it breaks the "center screen option" in some games, which gives an accurated feel to the original output.
Just tried it with Rayman 2 and the 10/10/2017 version, and I don't like it that much, so I'll stick with the version with overscan.

**Comment by ata4** [comment]
It's already an option in my local repo, just need to add the option to the settings GUI as well.

**Comment by TheRenegadist** [comment]
Has this been implemented yet because it seems Overscan is still present on games like GoldenEye even after ticking the button to hide it.
