### ISSUE TITLE
Unfiltered aspect ratio messed up

### ISSUE THREAD

**Issue by Phanatical** [ata4/angrylion-rdp-plus#23]
I noticed in various games I've tried that if you use unfiltered the aspect ratio goes all wonky. Indiana Jones and The Infernal Machine it stretches to a strange vertical aspect. Supercross 2000 it goes into an ultra widescreen view. These are just a couple examples, seems okay in Goldeneye and other games.

![project64 2017-09-29 10-27-18-07](https://user-images.githubusercontent.com/32393606/31020449-0ae9c0a2-a501-11e7-8e07-55d015e9f382.png)
![project64 2017-09-29 10-28-58-50](https://user-images.githubusercontent.com/32393606/31020456-0e68fc84-a501-11e7-9136-9842970203e7.png)

With filtered, aspect ratio remains perfectly intact. So I don't know why this happens.

**Comment by theboy181** [comment]
Are you using current build?

**Comment by Phanatical** [comment]
Yes, the Sep 29 build off emucr. I don't know how to compile myself. Also using latest Project64 and rsp.

**Comment by theboy181** [comment]
Looks like your correct, about it not working in latest. I'm sure it will get fixed soon.

**Comment by loganmc10** [comment]
Same issue in mupen64plus, lastest master

**Comment by Phanatical** [comment]
I just checked through all of the main releases so far and it looks like this issue has always existed with unfiltered. Would be great if this were fixable.

**Comment by theboy181** [comment]
Goldeneye is fixed with the current build. It used to make the window size change.

**Comment by Phanatical** [comment]
Yeah this problem doesn't seem to affect every game for some reason. Hopefully this and some performance issues with certain titles can be ironed out. Some games run full speed, others like Roadsters Trophy run at around 51fps even on an overclocked 4670k.

**Comment by ata4** [comment]
The plugin currently doesn't support aspect ratio correction for unfiltered output, so if a game decides to render with double/half vertical or horizontal resolution, the output is distorted. I hope I eventually understand the VI well enough to get rid of the overscan and obtain the correct aspect ratio at the same time.

**Comment by Phanatical** [comment]
Good luck, hope you can get it figured out. Really prefer using unfiltered. Can't you contact angrylion himself for help on this? I noticed his sourceforge page appears to be updated regularly so I'm guessing he's still around:

https://sourceforge.net/p/angrylions-stuff/activity/?page=0&limit=100#59cd08e45fcbc937826ed3db

**Comment by theboy181** [comment]
We should send him the invite to D if you think he would except.

**Comment by ata4** [comment]
For now, I'm simply locking the aspect ratio to 4:3 (or 16:9 with widescreen option enabled). I know it's not really the *correct* way to fix it, but after spending several hours studying the VI registers and angrylion's code, this seems the most convenient solution.
