### ISSUE TITLE
Filtered makes Bombers Notebook look weird in Majora's Mask

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#3]
Unfiltered works as expected as you can see here:

![unfiltered regular](https://user-images.githubusercontent.com/14175085/29867095-d12d4b42-8d7a-11e7-9094-7f97709b91bb.png)

The window/resolution when played with Unfiltered is very small, 320x240

However when you open the Bombers Notebook the window/resolution changes to something bigger (this particular screenshot is somewhere around 576x451 cropped)

![unfiltered bomb not book](https://user-images.githubusercontent.com/14175085/29867116-e49a9bda-8d7a-11e7-9402-e1559cf39e9a.png)

With Filtered it's a different story as you can see here:

![filtered](https://user-images.githubusercontent.com/14175085/29867357-99224e04-8d7b-11e7-9270-ed414f7adcf9.png)

There is clearly something off here as you can see the Sub-Screen menu behind it and if you unpause there is small garbage left behind on the bottom of the screen.

Toggling between Filtered and Unfiltered removes the garbage.

I assume Unfiltered is the way it's supposed to be because it's the Video Output causing least trouble (none)

**Comment by ata4** [comment]
I think I'll simply double the virtual resolution in unfiltered modes, so the size should be roughly the same as in filtered.

And I have tried to get rid of the frame garbage problem before, but it looks like I need to clear the buffer more frequently than I thought.

**Comment by SigmaVirus** [comment]
OK, well that's good to hear.

I kinda like the look Unfiltered gives me now, any chance of maybe keeping the old Unfiltered and name the new one Unfiletered 2x or something?

**Comment by ata4** [comment]
Turns out that a disabled part of Angrylion's original code had additional responsibilities. I've re-enabled it and it displays the Bomber's Notebook correctly now.

Looks like I've, once again, tampered too much with Angrylion's code without knowing what I'm doing...  🤦‍♂️

**Comment by SigmaVirus** [comment]
@ata4 Don't feel bad because you are doing a super job, kudos to you!
Thanks for fixing the issue, looking forward to try out next release.

**Comment by SigmaVirus** [comment]
I tested this earlier today and it worked perfectly!

I still prefer unfiltered nevertheless but I can say that this is the only plugin I use now and for the first time in many many years I feel like I'm beginning to feel there is major progress going on in the N64 scene.

I mean, who needs anything else at this point, this plugin accurately represents the experience I had when I was a young pre-teen back in the late 90's.
