### ISSUE TITLE
Vigilante 8 and V8'2 are slow

### ISSUE THREAD

**Issue by GamingTVYT** [ata4/angrylion-rdp-plus#30]
Is it possible to correct FPS problems in Vigilante 8 and 8'2 games? They are emulating perfectly, but in the phases they emulate between 15 to 25 FPS, which ends up leaving very slow .... any tips? Thank you . (My video card is (EVGA 1050 GTX - 2GB)

**Comment by SigmaVirus** [comment]
@GamingTVYT 

Are you using Project64 or Mupen64Plus? If you are on Mupen64Plus then you are pretty much limited to cxd4's RSP but if you are on Project64 then you at least have a choice of choosing between Zilmar's RSP or cxd4's RSP.

Zilmar's RSP is a lot faster, games like GoldenEye and Perfect Dark is always running fullspeed with it for me where's cxd4's RSP is causing slowdowns and especially in GoldenEye if explosions occur.

You are also just stating which graphics card you got, mind sharing which CPU too? I think this plugin is more CPU hungry then GPU hungry.

**Comment by AmbientMalice** [comment]
>I think this plugin is more CPU hungry then GPU hungry.

It's a software renderer. "It's CPU hungry" is a massive understatement.

**Comment by GamingTVYT** [comment]
@SigmaVirus I'm using (Project 64)
Video Plugin: angrylion's RDP Plus r4-52
Audio (sound) plugin: HLE Audio 1.8.2u1
RSP Plugin: 1.7.4.9999

My CPU: Intel Core i5 2310 CPU @ 2.90GHZ
Memory Ram (4GB)
Video Card: EVGA 1050 GTX 2GB
Windows 10 64 Bits

I want to buy a current processor and memory Ram Kingstom next month high speed, even this one I'm using and the processor, this Plugin is perfectly emulating several games, some titles that I did tests and were approved 100% only in this plugin video .

Mega Man 64; (no black stripes in the background)
Excite Bike64; (without bugs)
Resident Evil 2; (100%)
Mario Tennys (100%)
Star Wars Shadow of empire (the stars of the sky appear)
 
to other games that are emulating well now .... but only '' Star Wars Battle For Naboo '' is slow and '' Vigilante 8 and 8'2 are both emulating slowly in the game, despite the slowness, the game is emulating with the perfect graphics, with minimal bugs, 99% emulating perfectly.

Sorry my English, it's not my native language.

**Comment by SigmaVirus** [comment]
@GamingTVYT 

Thanks for your information!

From the looks of it I notice that you are using Shunyuans HLE audio plugin and from what I have heard and read about it it's bad (full coverage [here](http://forum.pj64-emu.com/showthread.php?t=3644))

Your setup is not high-end but not bad either and I would like you to try out Azimer's HLE Audio Plugin instead.

[AziAudio (17-10-08).zip](https://github.com/ata4/angrylion-rdp-plus/files/1384861/AziAudio.17-10-08.zip)

I'm not expecting miracles but I'm curious to see if it helps with performance for you a little on your current setup.

**Comment by LegendOfDragoon** [comment]
>Is it possible to correct FPS problems in Vigilante 8 and 8'2 games?

Maybe if someone optimizes the code more :smile: . Other than that, the best you can do is use the right emulator and plugins.

If you're using Shun's audio, don't use HLE for audio.

**Comment by GamingTVYT** [comment]
@LegendOfDragoon I've tested several Audio plugins, but the Vigilante 8 and V8'2 games, in addition to Star Wars BFN, continue to emulate slowly. I believe that in the next updates of the Plugin should be corrected the problem of slowness. Thank you for your attention, my friend. : D
![vigilante 8 2](https://user-images.githubusercontent.com/30762805/31585629-b39b5414-b1a3-11e7-8dda-90eb628a07ac.jpg)

**Comment by GamingTVYT** [comment]
@SigmaVirus I tried this plugin, but still slowly emulating the games (V8 / V8'2 / SWBFN), in the game menu, the speed is normal, in the choice of the phases, cars, everything ok, only when entering the screen to play stands slow, FPS rate that is 60 FPS, drops to 25 or 15, I used a new and more current Video Plugin emulating a little faster than before, I believe that in the next updates will be corrected this problem with these games. Thank you for your attention, my friend.

**Comment by SigmaVirus** [comment]
OK, well it was worth a shot at least and you seem to have way more Audio plugins than I have anyway.

I only use Azimer's Audio v0.70 WIP 7 but I couldn't help to notice that you also got the Azimer's Audio v0.70 WIP 7 XA2 which is the XAudio 2 version of the plugin, mind sharing and upload it here?

I can't seem to find a download of it anywhere?

**Comment by theboy181** [comment]
I noticed that  you don't get 60 DL's during the car select screen unless you turn on FAT in V8. Its weird like that.

**Comment by GamingTVYT** [comment]
@SigmaVirus I'll share my Audio Plugins folder.All Audio Plugins are in this folder, just extract it and put it in the Audio folder of the Emulator.
https://github.com/ata4/angrylion-rdp-plus/files/1385911/Audio.zip

**Comment by GamingTVYT** [comment]
@SigmaVirus @theboy181 I recorded a video demonstrating how the emulation at this moment, note that it is only slow when playing, this happens in all game screens.
If you want to see, the video is at this link. I tested with Audio Plugins.
https://www.youtube.com/watch?v=CIdpluF7CwU&feature=youtu.be

**Comment by SigmaVirus** [comment]
First of all thank you for the plugins, I appreciate it!

Second of all thanks for demonstrating your issue to us, I actually didn't know you could switch any form of plugins during emulation so I expected crashes.

As for the issue itself I was stunned how fast it went from smooth 60's down to a snails pace in the 20's something I haven't experienced myself before and the slowdowns I've had in GoldenEye with explosions is nothing compared to what we've seen here.

I don't own this game myself and before this issue I guess I never heard of it before either so it's completely new to me.

I don't know if it was an optical illusion or not but I noticed the frame rate got a little better with Azimer's Audio v0.70 WIP 7 XA2, close to 30's

**Comment by Phanatical** [comment]
I've encountered a number of games that run pretty slow unfortunately, seems to be rather random. Roadster's Trophy runs at around 45fps while racing. Vigilante 8 runs between 35-40 fps. The main menus in the NBA Live games chug as well. Yet the Star Wars games run fine. So it's a complete toss up, I haven't tested everything yet. Using P64 with 1.7.4.9999 rsp and Azimer's audio.

I'm on an i5 4670k overclocked to 4.1ghz. I'm thinking you'd need an overclocked i7 7700/6700k to get a steady 60fps in every title with this plugin. Hopefully down the line there can be some optimizations if it's even possible.

**Comment by LegendOfDragoon** [comment]
>I'm thinking you'd need an overclocked i7 7700/6700k to get a steady 60fps in every title with this plugin

Sadly I don't think 7700k is enough. Probably need Ryzen or maybe 8700k.

> I believe that in the next updates of the Plugin should be corrected the problem of slowness.

That's a bit too optimistic, my man. 

>I've tested several Audio plugins

Audio plugins will hardly impact performance. Shunyuan's is a special case, because his "HLE" is actually slower than LLE lol, so Never use HLE with his plugin.. I guess it wouldn't hurt to use Azimer's with HLE, if you needed to squeeze a little extra performance for maintaining full speed.

**Comment by ata4** [comment]
Vigilante 8 apparently renders 4 identical frames in a row and then only outputs the last one. No idea why... but it definitely doesn't help with the performance.
