### ISSUE TITLE
Perfect Dark crashes on angrylion's RDP Plus r5 with Unfiltered as startup value 

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#32]
This issue is happening yet again I'm afraid, I have tested the latest r5 release on both Project64 2.4.0.9999 from 2017-10-03 and the m64p project from 2017-10-22 and it's the same issue as last time.

Perfect Dark is really sensitive to this and no other games that I own is crashing with Unfiltered set to startup value.

It's dead easy to reproduce too, start with a fresh angrylion-rdp-plus configuration on Project64 or mupen64plus-gui and change Filtered to Unfiltered.
Then save and close either emulator, start Perfect Dark and BAM a crash.

Thanks in advance!

**Comment by SigmaVirus** [comment]
@ata4 

Comparing https://github.com/ata4/angrylion-rdp-plus/blob/master/core/vi.c from the time you [fixed issue 19](https://github.com/ata4/angrylion-rdp-plus/commit/d0031a5347f9e57ea08c6990480024911d5bf56d) and to how it looks today your previous fix is not even there anymore and there is roughly 815 lines of code gone?

This would explain why this is happening all over again.

**Comment by SigmaVirus** [comment]
@ata4 
I created a pull request that hopefully fixes this issue, it's the same fix you used the last time for #19

If it's correct then feel free to merge it, if you intentionally removed it then this issue might have to be fixed in some other way.

As for the lines of code I referred to earlier that were gone I noticed in the older vi.c file that there was a lot of empty space, I guess you cleaned it up.

**Comment by ata4** [comment]
I merged some code parts together for less redundancy. Looks like I accidentally dropped the previously introduced check, so I'll just add it again.
