### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by loganmc10** [ata4/angrylion-rdp-plus#34]
```
vi.c(750): error C2220: warning treated as error - no 'object' file generated [C:\mg\angrylion-rdp-plus\core\core.vcxproj]
vi.c(750): warning C4098: 'vi_update': 'void' function returning a value [C:\mg\angrylion-rdp-plus\core\core.vcxproj]
```

Mupen64plus build in Visual Studio

**Comment by loganmc10** [comment]
I believe this is the offending line:

https://github.com/ata4/angrylion-rdp-plus/blob/master/core/vi.c#L750

```return 0``` should be ```return``` in a void function @ata4

**Comment by twinaphex** [comment]
Just push a PR for this already. It's clearly an error, and I already fixed this in our fork. No point pointing it out in an issue when you can just push a PR already.

**Comment by loganmc10** [comment]
I'm on my phone, I'll submit a PR tomorrow if it hasn't been fixed by then

**Comment by SigmaVirus** [comment]
I don't know how it came to be like this?

It's sad really and I thought we all strived for one thing, having fun and play games but that must have changed drastically and I'm having no fun at all when we have this attitude to each other @twinaphex

Anyway I have submitted a PR that hopefully fixes this, if it's good then merge it.

I really hope we can get along and start having fun again, I for one just want to play my games and not have silly arguments all the time that contributes with nothing.

**Comment by twinaphex** [comment]
@SigmaVirus I stopped having fun months ago after loganmc10s trolling and harrassment, unprovoked too. I keep reaching out too to see if we can settle this, instead he wants to keep ignoring me and continue being deliberately annoying and trollish while never wanting to end this silly self imposed beef.
