### ISSUE TITLE
Serious performance issues on latest builds

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#37]
I don't know what have happened to the plugin but now I got serious performance issues with practically all games I have in my collection.

I have been using [r5-6-dirty](https://github.com/ata4/angrylion-rdp-plus/files/1417973/angrylion-plus.17-10-25.zip) for a good while now and performance have been great!

On [r6-56](https://github.com/ata4/angrylion-rdp-plus/files/1469745/angrylion-plus.17-11-13.zip) the performance is very very bad and I rarely get full speed anymore.

There have been quite a lot commits between r5-6-dirty (https://github.com/ata4/angrylion-rdp-plus/commit/13c4b894130806ac64a094802c8cb9d4d1a7e74e) and r6-56 (https://github.com/ata4/angrylion-rdp-plus/commit/eef64660d59054daf10504ba5c3af612ee5a2cdd) and the size of the plugin have shrunk from around 607kb to 492kb

To put it simple, games are running slow as if you were using vanilla angrylion.

**Comment by ata4** [comment]
The recent changes contain some bigger changes to manage thread-local storage myself, since some compilers are known for their extremely inefficient implementations in certain situations. The rest is some restructuring to merge some code pieces and simplify the connection between the internal and the plugin interfaces.

While it does hurt Windows performance a bit, it definitely shouldn't degrade it to single-threaded performance. Are you sure you have selected multi-threaded rendering in the options? If so, maybe adjust the number of workers a bit. On both my and theboy181's system, the most recent commit still seems to run pretty fast.

**Comment by SigmaVirus** [comment]
Thanks for your input!

I have to look at this deeper tomorrow morning, usually when I try a new build out the only thing I change is the Video Output Filtered/Unfiltered, the rest just works out of the box.

I have never touched any of the multi-threaded rendering options in the past so I don't know what numbers I need to put in, it's currently set to 0.

**Comment by ata4** [comment]
0 means it uses all available processors, both physical and virtual. You could try lower numbers, for example. Maybe just the number of physical cores.

**Comment by theboy181** [comment]
@SigmaVirus This plugin is running great for me! There are a couple of things I would check for, make sure that you don't have CPU set to interpreter, and make sure sync to audio is not used.

I would say that the performance is better than way better than r4-56, and at par of r5-1 dirty

**Comment by theboy181** [comment]
r6-56
![image](https://user-images.githubusercontent.com/9299743/32800043-36bcb7ec-c92e-11e7-9182-b55712875d6f.png) Filtered
![image](https://user-images.githubusercontent.com/9299743/32800084-48d21760-c92e-11e7-8c93-4beb34b01aa4.png) Unfiltered

r5-1-dirty (last build I had)
![image](https://user-images.githubusercontent.com/9299743/32800231-9cf7f224-c92e-11e7-998f-a1c3d355aa68.png) Filtered
![image](https://user-images.githubusercontent.com/9299743/32800274-b862b1c0-c92e-11e7-9caa-45430d5b9954.png) unfiltered

I noticed that the FPS was a little more spastic on the latest build, so it was harder to capture the speed int he screen captures. After the r5-1 build there was a slight regression in Windows speed after the Linux improvements. @barracuda is aware of the regression.

**Comment by SigmaVirus** [comment]
Thanks for your replies guys but I have found out what the problem was.

The problem was that the Multi-threaded checkbox wasn't ticked by default in the new build but was ticked by default in older builds.

One tick later and it's fullspeed again in r6-56!

So there is nothing wrong, closing this now...

**Comment by ata4** [comment]
Yep, the default options of previous versions aren't implemented yet. It's all WIP right now.

**Comment by SigmaVirus** [comment]
Thanks mate for the heads up!

I was so blind that I just used r6-56 like all the other older builds and didn't even thought about that the Multithreaded checkbox was unticked.

I'll make sure that I look at the settings dialog windows a bit more carefully next time!
