### ISSUE TITLE
[Suggestion] Ability to save changed settings

### ISSUE THREAD

**Issue by SigmaVirus** [ata4/angrylion-rdp-plus#4]
As I'm currently using Unfiltered majority of the time right now I was just wondering if you have plans for implementing saving changed settings preferably to a .ini or .cfg file?

That would be really great and help a lot when testing things further.

I know I have created a few things here already but this is what I got at the moment, great job otherwise @ata4 

I'll keep on testing things as much as I can, thanks in advance!

**Comment by ata4** [comment]
It's definitely planned for the next release, I'm not sure about the config file format or storage location yet, though.

**Comment by SigmaVirus** [comment]
As a reference, GLideN64 uses the Project64/Plugin/GFX folder for both GLideN64.custom.ini and the GLideN64.ini configuration files so the GFX folder would be a good storage location.

And besides most of the other 3rd party plugins uses the corresponding folders under the Project64/Plugin folder.

As for the file format, well most plugins tend to use the .ini format but in the end it's up to you what you will choose.

**Comment by ata4** [comment]
It's definitely planned for the next release, I'm not sure about the config file format or storage location yet, though.

**Comment by SigmaVirus** [comment]
This seems to be implemented already as there is a angrylionplus-config.bin file in the Project64/Plugin/GFX folder and the settings are saved properly so I'm closing this.

**Comment by ata4** [comment]
Yes, that's right. Sorry, I forgot to reference the issue in the corresponding commit.
