### ISSUE TITLE
Feature request - Option for linear scaling instead of nearest neighbor

### ISSUE THREAD

**Issue by LMLB** [ata4/angrylion-rdp-plus#47]
The screen looks pretty pixellated as it is now.

**Comment by ata4** [comment]
It's definitely possible and I did some tests before, but it's *very* blurry. I've also experimented with the alternative to only use linear filtering for the vertical scaling and then nearest neighbor for the upscaling, but it's somewhat tricky for games that use interlacing.

**Comment by LMLB** [comment]
I tried changing [these lines in plugin-common/gl_screen.c](https://github.com/ata4/angrylion-rdp-plus/blob/3e036dac21f4d6e3fe425657fa31b9968fbe432c/plugin-common/gl_screen.c#L139-L140) from `GL_NEAREST` to `GL_LINEAR` and I think it looks good. Here is a screenshot from Project64: 
![Project64 screenshot](https://user-images.githubusercontent.com/6322603/34071266-073a3d00-e274-11e7-8205-a604bd230b18.png)

**Comment by ata4** [comment]
It looks okay in 640x480, but it's pretty blurry in 1080p, for example. That's why I prefer the two-step upscaling.

**Comment by LMLB** [comment]
All I really want is an option for some kind of upscaling that doesn’t look pixelated like it currently does. For me, a simple bilinear is better than nothing, even in 1080p (as long as I’m not too close to the screen).

**Comment by ata4** [comment]
Okay, I'll add an option to switch between linear and nearest-neighbor filtering for now. I may add that alternative filter mode in the future as well.

**Comment by SigmaVirus** [comment]
@ata4 
THANK YOU for this, truly THANK YOU!

The games look a thousand times better with Linear both with Filtered and Unfiltered, PERFECT commit mate!

**Comment by ata4** [comment]
You're welcome. 😉
