### ISSUE TITLE
GoldenEye runs slow

### ISSUE THREAD

**Issue by Graslu** [ata4/angrylion-rdp-plus#52]
On the latest WIP build from January 10th (r6-94) GoldenEye runs incredibly slow while older versions ran it fine. Perfect Dark in the other hand, runs perfectly fine with no drops with the WIP build. 
Could this be related to how GoldenEye has no z-buffering?
I'm using the latest Project64 developer build.

Specs:
i7-3770@4.3GHz
GTX 1070 OC 8GB

**Comment by Graslu** [comment]
Yeah it's enabled. I tried with disabled, auto and manually setting the amount of threads.

**Comment by theboy181** [comment]
Did you build it or download from the updates that ghost provides? the build from Jan 10th runs about the same speed for me ..  Where exactly do you notice the regressions?

**Comment by Graslu** [comment]
I downloaded the updates provided by Ghost. The drops are in-game and not in the menus. Statue is where I started noticing all the drops. With the previous version I played the full game (Except bonuses) just fine. I find it weird because Perfect Dark works much better despite being more graphically intense.

**Comment by theboy181** [comment]
This game uses heavy alpha fort explosions.. its um-optimized really.

**Comment by Jj0YzL5nvJ** [comment]
I don't see speed penalties in GE using mupen64plus + 0e9f50351843b0c93db611353e634d39a9b66b14 and de37833335dab98eceb26bccbd86059d5a633712 . Compared to the current version (5c8b788e44e4a25d60b177cff30a00366c13037c).
**SigmaVirus** (ghost) apparently deleted his account ...so there will be no plugin for Project64 in a while ^^u

**Comment by Graslu** [comment]
I tried using the latest mupen64plus version and it runs even worse, including earlier levels. I'm out of options here it seems.

**Comment by Jj0YzL5nvJ** [comment]
Can you see the difference in performance change between mutithread (Parallel) enabled and disabled?

**Comment by Graslu** [comment]
Yeah that's the one I'm using, no difference between 32 or 64-bit, nor Parallel enabled or disabled.

**Comment by Jj0YzL5nvJ** [comment]
That sounds very bad ...let's make something clear first.
 In the case of the Project64 plugin, the last plugin that works correctly for you is angrylion-plus (18-01-09).zip (de37833)?

**Comment by Graslu** [comment]
That's correct, the January 9th version works fine for the most part, it struggles at times on levels like Statue or the watch menu but stays around 60 VI/s for the most part.
January 10th version struggles on most maps, drops below 50 VI/s at times too.

I tried the Mupen64plus version on the same levels (Dam, Facility, Statue) and it lags on all of them, it's all stuttery. January 9th palys Dam and Facility stuck at 60VI/s and Statue fine for the most part.
![jan9](https://user-images.githubusercontent.com/34986384/36800793-abb62e5e-1cb0-11e8-9e5c-b1071a3eeb8b.png)
![jan10](https://user-images.githubusercontent.com/34986384/36800804-b2e3798e-1cb0-11e8-9932-da7a6cef78db.png)

**Comment by theboy181** [comment]
GoldenEye 007 (U)
30 FPS Hack

810064D8 0C01
810064DA 8800
810064E0 0C01
810064E2 8806
81062000 3C07
81062002 8005
81062004 240E
81062006 0002
81062008 ACEE
8106200A 8498
8106200C 2407
8106200E 0002
81062010 0800
81062012 0B36
81062018 3C07
8106201A 8005
8106201C 240E
8106201E 0002
81062020 ACEE
81062022 8498
81062024 2407
81062026 0002
81062028 0800
8106202A 0A04
810010CE 0000

Note: This hack with PJ64 2.4.X CF=1,  OC=2 and AL+ RDP = GOLD!

**Comment by Graslu** [comment]
That works great, thanks for the code and settings! It now stays at constant 60 VI/s all the times, the only issue is the slow-motion intro but that's hardcoded cycles so can't do much about it. 
This should be a great fix until we're able to run GE fullspeed without any hacks, like Perfect Dark.

**Comment by theboy181** [comment]
You on discord64? You can find the link there http://n64dev.org/ Always looking for new scene members.

**Comment by ata4** [comment]
I may need the save states for the levels where the slow downs happen. In my test, I can't see any difference between r4 and the most recent build in the first level.

**Comment by Graslu** [comment]
Sent them on Discord, hope it helps!

**Comment by Jj0YzL5nvJ** [comment]
@Graslu, test my build. #29

**Comment by Graslu** [comment]
Seems to have an improvement on performance, Statue didn't lag unless I get close to a grenade and otherwise it's working fine. The issue is that the video settings window is broken and when you try to open it the emulator will hang.

**Comment by Jj0YzL5nvJ** [comment]
> The issue is that the video settings window is broken and when you try to open it the emulator will hang.

For the GUI it is necessary to compile with the IDE, devenv or msbuild ...I reuse to use the first two.
Try the new one.
