### ISSUE TITLE
Major League Baseball with Ken Griffey Jr. (Messed Up Splash Screens and Start Screen)

### ISSUE THREAD

**Issue by pdrome** [ata4/angrylion-rdp-plus#53]
Upon starting the game the splash screens tear/flash. The symptoms appear using angrylion plus, when using cxd4 or hle rsp, and when using the dynarec, cached interpreter, and pure interpreter (in m64p, February 5th 2018 release). I've also verified the behavior in parallel n64 when using angrylion with cxd4 and the dynarec.

Here is a video comparing the opening with angrylion in m64p, gliden64 in m64p (which has similar behavior), and parallel n64 (with parallel rdp) in retroarch which seems to have the correct behavior.

[![Video showing issue](https://img.youtube.com/vi/DRhHEgIFscw/0.jpg)](https://www.youtube.com/watch?v=DRhHEgIFscw "Video showing issue")

**Comment by ata4** [comment]
Hm... I can confirm it happens in Project64, too. It's less severe with vanilla Angrylion, but still not correct. I'll try to figure out what's going on here.

**Comment by pdrome** [comment]
There's also an outstanding issue in GlideN64 for the same thing.  Just in case it's useful:

gonetz/GLideN64#1664

**Comment by pdrome** [comment]
gonetz/GLideN64#1664

**Comment by pdrome** [comment]
gonetz/GLideN64#1664

**Comment by ata4** [comment]
Just a small update: using a counter factor of 1 seems to fix the issue, at least in Project 64. So it's probably a timing issue.
