### ISSUE TITLE
Taking a screenshot is broken

### ISSUE THREAD

**Issue by rez-** [ata4/angrylion-rdp-plus#54]
Unfortunately, taking a screenshot crashes m64p (build date: 22 jan 2018) with angrylion-plus GFX plugin (latest, 7adc5d6)

**Comment by fzurita** [comment]
In here:
https://github.com/ata4/angrylion-rdp-plus/blob/master/plugin-mupen64plus/gfx_m64p.c#L226

before calling ```screen_read``` for the first time, this needs to be set: ```buffer.pixels = NULL;```

**Comment by ata4** [comment]
Right, I was missing something there... I fixed it by initializing the entire struct to zero, just to be sure.
