### ISSUE TITLE
StarFox 64 - pixel noise 

### ISSUE THREAD

**Issue by Kidboy17** [ata4/angrylion-rdp-plus#56]
Just want to say that I stumbled on this plugin today and I'm really pleased with what it does. Games run at 60fps while producing everything almost perfectly!  I am using Project 64 2.3.2 with the RSP that it comes with. Have not experienced any game breaking issues.

There is pixel noise in the background of space in the intro and also in-game. I've provided screenshots to clear things up. Is this caused by the low-res of this plugin? This does not get reproduced if I use Glide64 or any other HLE plugin.

![starfox64](https://user-images.githubusercontent.com/37382324/37444934-c911c2c0-27d1-11e8-8cd7-392767b69b69.png)

![starfox64_1](https://user-images.githubusercontent.com/37382324/37444936-cee78964-27d1-11e8-8a1a-24b938ae344d.png)

**Comment by Boviligg** [comment]
It's meant to look like that.

**Comment by Kidboy17** [comment]
Oh ok. I'll go ahead and close this.
