### ISSUE TITLE
Future goals with the project?

### ISSUE THREAD

**Issue by ghost** [ata4/angrylion-rdp-plus#57]
This isn't an issue per se, just me wondering what the current goal for this project is?

It's a pretty darn good plugin today as it is that faithfully replicates the look and feel of the N64 and it has only got better the more it have been worked on.

@ata4 

What are you're future goals with this excellent plugin? I know there is only so little time every day/week/month/year you can work on this and I'm just curious, what's left to improve?

**Comment by ata4** [comment]
Yeah, the plugin works pretty well already, but here's what comes into my mind right now:

* Deinterlacing (or just being able to disable interlacing, if possible)
* GLSL VI filter for more speed (appears to be difficult)
* Other shader features (scanlines?)
* Performance improvements on non-Windows platforms (working on it right now)
* Minor bug fixes (the shadow in Conker's intro, for example)

**Comment by TheLocoBandito** [comment]
Thanks @ata4 for answering, seems like good and doable goals to strive for!

**Comment by fallaha56** [comment]
exciting plans :))

the interlacing thing is interesting, just curious, are there hard n fast rules about this? -e.g. can the N64 do high-res interlaced 480i/576i@60fps or is it a 480p/576p@30fps image that is output interlaced? or is it all on a per-game basis?

also, don't know if it's any help but FinalBurnAlpha and MAME had great PAL/NTSC-type filters to give that CRT look...think those were HLSL

[http://eab.abime.net/showthread.php?t=66712](http://eab.abime.net/showthread.php?t=66712)

**Comment by RokkumanX** [comment]
@ata4 

Since this issue was opened how much of the goals do you estimate have been more or less finished?
Are you happy with what the plugin is today?

r8 is an amazing release so far and I'm loving it. I don't own all games for the system so there is bound to be bugs and issues still present but on the small percent I own I got little to none issues with the plugin today.
