### ISSUE TITLE
Possible linux version precompiled?

### ISSUE THREAD

**Issue by mrdeathjr28** [ata4/angrylion-rdp-plus#59]
Hi
Maybe can possible add linux support aka mupen64plus
Thanks

**Comment by ata4** [comment]
Should be possible already. You have to build it yourself, though.

**Comment by mrdeathjr28** [comment]
@loganmc10 

Exactly precompiled is more affordable for most users

**Comment by ata4** [comment]
I can include a build for Ubuntu LTS 18.04 in the next release. That's the system that I use for testing.

**Comment by mrdeathjr28** [comment]
@ata4 

Many thanks
