### ISSUE TITLE
feature: vsync option

### ISSUE THREAD

**Issue by Xenphor** [ata4/angrylion-rdp-plus#64]
For emulators that don't have a builtin vsync option like Project 64, I think it would be nice to include a vsync setting in the video plugin. Mupen64plus has a vsync option within the emulator itself, and it appears to work well with no stuttering in angrylion, so having the ability to do that with project 64 would be nice since the performance is much better there. 

I've tried forcing vsync at the driver level but still get stuttering. This is on Windows 10, 1050 ti, 8700k. This is of course with games already running at full speed.

**Comment by ata4** [comment]
I've added the option in commit 422a7d80dae62c6c1fd5a20a932f129416c4e0b1.
