### ISSUE TITLE
Mario Tennis - Unfiltered - left part of the screen is rendered on the right side

### ISSUE THREAD

**Issue by Pixelnarium** [ata4/angrylion-rdp-plus#65]
I am using m64p on ArchLinux here. This does not happen in filtered mode. I also tried some other games like Mario 64, Blast Corps, Turok and Mario Golf and it does not happen there.

![mtal](https://user-images.githubusercontent.com/30435935/42207149-7c1718c4-7ea9-11e8-9c29-36ce033d81d1.png)

**Comment by theboy181** [comment]
This happens on angrylion when unfiltered too. @ledgendofdragoon had a work around for this in he’s tests.

**Comment by Tasosgemah** [comment]
Maybe it's an overscan thing? Meaning that it happens on real hardware but it's hidden?

**Comment by theboy181** [comment]
I think this happens on the real hardware if you disable the filters too. I would need to test again to be sure though.

**Comment by Pixelnarium** [comment]
How can I disable the filter on real hardware? Do I need an UltraHDMI for that? I "only" have an Everdrive but I can't find a "disable AA" cheat for Mario Tennis. But maybe this is a different thing.

**Comment by theboy181** [comment]
There is a few lists with aa codes around. Usually they are applied via cheat codes.

**Comment by LegendOfDragoon** [comment]
Lack of VI filter isn't causing this issue. It's the fact that his code for non-Vi filter displays extra pixels. Angrylion did tests on real hardware and determined that a certain number of pixels in each row are never displayed (first few and last few pixels). It's easy to fix.

**Comment by theboy181** [comment]
Thanks, I thought we had tested this. Why did t al fix this issue then?

**Comment by Pixelnarium** [comment]
I think this would explain some other observations I made. Ms. Pac-Man and Virtual Pool 64 have the same problem like Mario Tennis. Virtual Pool 64 just on the left side.

In some games it looks like this:
![pw](https://user-images.githubusercontent.com/30435935/42391436-ac3096a4-814f-11e8-8727-1fc47fa74e02.png)

**Comment by ata4** [comment]
Hm... I could easily fix it, but the question is: how many pixels should be removed from the left and right? In filtered, it's 8. But in filtered, the width is always 640, unlike in unfiltered.

**Comment by LegendOfDragoon** [comment]
>Why did t al fix this issue then?

He never implemented non-Filter.

>But in filtered, the width is always 640, unlike in unfiltered.

I would just see where it would normally start after scaling width to 640.

**Comment by ata4** [comment]
Okay, I'm using the filtered mode for reference and just rescale the cropped area to unfiltered. That appears to work just fine for most games, but it needs more testing.
