### ISSUE TITLE
StarCraft - horizontal garbage lines in game (only in parallel mode)

### ISSUE THREAD

**Issue by Pixelnarium** [ata4/angrylion-rdp-plus#66]
I am using m64p on ArchLinux here. This does not happen in single thread mode. These lines are jumping around and are not static. Also the amount of lines changes all the time.

![sc](https://user-images.githubusercontent.com/30435935/42242918-e8ed15d2-7f0f-11e8-820f-197667087368.png)

**Comment by Pixelnarium** [comment]
fyi: The issue is gone by setting the new DpCompat value to "2". You can close the issue if you want or tag it that this game needs this.

**Comment by ata4** [comment]
Ah, good to know it fixes the issues in this game as well. I guess I'll need a list of game-specific options sooner or later.
