### ISSUE TITLE
Command & Conquer - Static noise is blocky in parallel mode

### ISSUE THREAD

**Issue by Pixelnarium** [ata4/angrylion-rdp-plus#67]
I am using m64p on ArchLinux here. This does not happen in single thread mode.

Single Thread Mode:
![ccsingle](https://user-images.githubusercontent.com/30435935/42244510-9827f5b2-7f15-11e8-9d78-f2d737120337.png)

Parallel Mode:
![ccparallel](https://user-images.githubusercontent.com/30435935/42244515-9f157a70-7f15-11e8-9cf6-d280739dbae5.png)

**Comment by Pixelnarium** [comment]
Same (?) with Hybrid Heaven in the intro:

Single Thread:
![hhsingle](https://user-images.githubusercontent.com/30435935/42244888-039ea9fc-7f17-11e8-9154-955cf40a1e8d.png)

Parallel:
![hhparallel](https://user-images.githubusercontent.com/30435935/42244892-0899806c-7f17-11e8-8c5c-e1101ee5a195.png)

**Comment by ata4** [comment]
Hm, that's very interesting. I think I have to use random seeds for each worker to avoid these artifacts.
