### ISSUE TITLE
For "Force 16:9 widescreen", support alternative aspect ratios?

### ISSUE THREAD

**Issue by AWBuchanan7** [ata4/angrylion-rdp-plus#68]
How approachable would it be to support alternative aspect ratios such as 21:9 "Ultrawide"? This currently isn't supported from what I can tell, but I'd love to see this for sure!

**Comment by Jj0YzL5nvJ** [comment]
I don't think it's a good idea or even possible to put a **widescreen hack** on a LLE plugin based in other "pixel-perfect" LLE plugin. The current multi-threaded rendering can break many things, I don't want to see what a **widescreen hack** could do.

 @AWBuchanan7, what you seek is HLE. I recommend you [GLideN64](https://github.com/gonetz/GLideN64), it even support stereoscopic rendering in a fork.

**Comment by ata4** [comment]
Agreed, 4:3 and 16:9 are the only aspect ratios that were ever officially used on the N64. Anything else only works with ROM hacks, and also only in theory, since most hacks are tested with HLE.

**Comment by AWBuchanan7** [comment]
No worries - your reasoning makes sense. HLE is great and all, I just love the "unfiltered" look I can get with angrylion that I don't seem to be able to pull quite so much with something like GLideN64. I'm more than happy to stick with 16:9 though. Cheers!
