### ISSUE TITLE
Mouse interaction glitches after a short while.

### ISSUE THREAD

**Issue by retrobenny** [ata4/angrylion-rdp-plus#7]
I am using the latest r3 version of the plugin.

I opened Banjo-Tooie with PJ64 2.4.0-444 with a command line shortcut to only use my 2 physical cores and after I stretched the window to a larger more comfortable size on my 2048x1368 screen resolution some moment later,my mouse stopped interacting with PJ64 and everything else.

I had to use ALT+TAB to regain access to mouse interactions (clicking/visual cues of hovering/etc.) and once I clicked on the PJ window again the issue returns.

I have mostly accurate settings set just to test some things and didn't expect this odd issue to occur.
I am on a dual-core (4 threads/2 logical) Intel i5 6200U via an ULV laptop with the cores unparked.

When forcing PJ64 to only use the 2 physical cores,it runs faster (other plugins) than leaving it to use all threads.

**Comment by ata4** [comment]
I haven't encountered this issue so far and also can't really explain it. The cursor should only be hidden when PJ64 is in fullscreen mode, either by pressing alt+tab or by enabling it in the options. In normal windowed mode, it should never disappear just by resizing the window, at least I can't explain it by looking at my code.

**Comment by SigmaVirus** [comment]
I can't reproduce this at all, everything is working normally as intended.
