### ISSUE TITLE
Killer Instinct 1.0

### ISSUE THREAD

**Issue by theboy181** [ata4/angrylion-rdp-plus#71]
When you disable filters for this game the title screens resolution is lowered. 

![image](https://user-images.githubusercontent.com/9299743/42726337-8af0be8a-8747-11e8-8130-b325c0b3e85b.png)

Changing the last bit in memory location 802CA060 to a 9 fixes the issue. It looks like some flag for how the game is displayed is set here. 

Can you have filtered mode properly set the best flags for games when they are filtered and use interlacing like this game does? 
![image](https://user-images.githubusercontent.com/9299743/42726334-8260938a-8747-11e8-911b-bfed38fb229a.png)

https://dragonminded.com/n64dev/Reality%20Coprocessor.pdf  <-- there are some great examples of the modes in this DOC.

**Comment by LegendOfDragoon** [comment]
What is that value normally set to? Does this code also affect the in game graphics?

**Comment by theboy181** [comment]
During the interlaced parts this area of memory is set to 8. I’m actually trying to see if I can trick the game into running interlaced mode when in game too

**Comment by gamemasterplc** [comment]
This issue is because the game uses the high-resolution mode which angrylion has poor support for in menus.

**Comment by theboy181** [comment]
A lot of the menus are working. What examples do you have
