### ISSUE TITLE
Nothing opening, GLIBC & MUSL

### ISSUE THREAD

**Issue by johnny-mac** [ata4/angrylion-rdp-plus#72]
Hello. I have compiled your plugin for Arch Linux GLIBC & Void Linux MUSL, but it just sticks at "unnamed window" & doesn't load anything. I have tried compiling it from the latest git clone & from the latest release but I get the same result on both.... Is this not in working order, or...?

**Comment by theboy181** [comment]
What rsp are you using?

**Comment by johnny-mac** [comment]
HLE & z64, the only two I have.... Is there supposed to be another one somewhere?

**Comment by theboy181** [comment]
Are you setting the RSP to LLe?
