### ISSUE TITLE
Glitched shadows on CBFD

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [ata4/angrylion-rdp-plus#74]
Using `Parallel = True` on CBFD with mupen64plus, give as result to incorrectly rendered shadows in the game opening.

Parallel = False
https://0x0.st/s3ZS.png

Parallel = True
https://0x0.st/s3ZQ.png

**Comment by ata4** [comment]
Duplicate of #12. It's a known bug that is pretty tricky to fix without killing the performance. I hope I'll be able to fix it one day, though.
