### ISSUE TITLE
Swapped color channels in Project64

### ISSUE THREAD

**Issue by jonathan25** [ata4/angrylion-rdp-plus#77]
I built the latest version of the plugin (r7 77) and tested it in Project64.

I noticed that two color channels were swapped (red <-> blue).

![smash brothers_0000](https://user-images.githubusercontent.com/8753093/47062748-07715400-d195-11e8-9a37-2a5376e1b753.png)

Then I found that this issue was present since this commit: https://github.com/ata4/angrylion-rdp-plus/commit/585694f1c4af4e5e230b48ad3c3143536d2a9884

I changed the file `src/plugin/common/gl_screen.c`, this line:
`#define TEX_FORMAT GL_BGRA`
to
`#define TEX_FORMAT GL_RGBA`

and it seemed to solve the problem. I don't know if this is a issue only with my machine or OpenGL since that line is inside an `#ifdef`

**Comment by Jj0YzL5nvJ** [comment]
I can't reproduce this issue on the NVIDIA and AMD GPUs. This is possibly a bug in the Intel drivers.

Possible related issues:
https://github.com/gonetz/GLideN64/issues/1812
https://github.com/gonetz/GLideN64/issues/1829

Another mention:
```
September 10, 2010:
	If Mednafen is running with an OpenGL implementation of OpenGL >= 1.2, and is on an x86 or x86_64 platform,
	it will now upload texture data in GL_BGRA GL_UNSIGNED_INT_8_8_8_8_REV format rather than GL_RGBA GL_UNSIGNED_BYTE.
	This may need to be tweaked for older video cards.  Would it have killed the OpenGL developers to have
	included a means of querying the fastest formats for texture uploading?
```
[Source...](https://mednafen.github.io/documentation/ChangeLog.txt)

**Comment by ata4** [comment]
Well, that's annoying. I also can't replicate this bug, but if it's indeed an Intel driver bug, then I may have to create a workaround, which may make OpenGL ES support a bit more complicated.
