### ISSUE TITLE
Hide Overscan doesn't completely remove Overscan

### ISSUE THREAD

**Issue by TheRenegadist** [ata4/angrylion-rdp-plus#78]
Seems both the stable and dirty version of AL ADP+'s "Hide Overscan" feature only removes a tiny fraction of the overscan from NTSC ROMs (Tested on GoldenEye so far). Is there something in-dev to strengthen the toggle so it removes all if not most of the Overscan from these games?

**Comment by gamemasterplc** [comment]
Some games will apply the overscan using the RDP like Super Mario 64 and therefore are unaffected by the feature.

**Comment by TheRenegadist** [comment]
Is some kind of stretching toggle planned then to remove as much of the overscan as possible? I've resorted to using a PAL ROM to play because the overscan is much less of an issue at the cost of not being able to use ROM hacks.

**Comment by ata4** [comment]
Only the overscan that is defined by the VI can be removed reliably. Anything that happens in the framebuffer itself can only be detected by heuristics, which would be unreliable and slow.

**Comment by gamemasterplc** [comment]
Unless if you leave it configurable by the user of how much to remove.

**Comment by TheRenegadist** [comment]
Sorry to go off-topic but I've gotten used to the overscan on NTSC copies now. My main issue is dropping frames in GoldenEye, a good chunk of the time I can keep a steady 60 VI but there's times it dips to 57-58 and when looking directly at explosions/smoke effects it drops down to 32-48 and comes to a crawl until the effect has worn off or I look away.

I'm using a 7700k that isn't overclocked and I'm wondering if anyone else is having the issue with this CPU and if so would overclocking it provide a steady 60VI no matter what. I've never overclocked anything before and I'm hopping that if I do need to overclock it I won't need to spend the money on new parts to accommodate. Many thanks!

**Comment by Jj0YzL5nvJ** [comment]
[Sounds like accurate emulation...](https://github.com/gonetz/GLideN64/issues/1381)

**Comment by itsmattkc** [comment]
^ this, GoldenEye on N64 was painfully slow at times, especially with a lot of explosions and smoke on screen.

**Comment by TheRenegadist** [comment]
I wouldn't mind it so much if the audio didn't crackle, I assume there isn't a fix for that?

**Comment by TheRenegadist** [comment]
Current FPS while streaming: [https://youtu.be/AC2ZIxjL6fs](url)

I'm going to update both my CPU and my GPU in an attempt to get better performance but I'm not sure it will help.

**Comment by TheRenegadist** [comment]
So anything on this like a possible fix or change so that we can remove the overscan, even at the cost of graphical issues?
