### ISSUE TITLE
Build errors with latest changes

### ISSUE THREAD

**Issue by theboy181** [ata4/angrylion-rdp-plus#8]
Will no longer build with one click.

**Comment by ata4** [comment]
Well, I'll need an error message or something to investigate. 😉

**Comment by theboy181** [comment]
Closing now that i know you need python3 installed for git version numbers.

**Comment by theboy181** [comment]
Issue got worse. After installing Python3, and manually trying to remove items from the source, Im getting a new error with glscreen.lib

**Comment by loganmc10** [comment]
Yes it is from this commit (see my comment):

https://github.com/ata4/angrylion-rdp-plus/commit/9503b4ae701d27a4971ed32cf359b17c0cad7a76#commitcomment-24149052

**Comment by theboy181** [comment]
looks like there is a spelling mistake in the link file.. missing a dash gl-screen.lib

**Comment by ata4** [comment]
Yep, didn't notice it because I had still a glscreen.lib in my build folder... should be fixed now.
