### ISSUE TITLE
New options vsync and exclusive full screen do not save to the angrylion ini file. 

### ISSUE THREAD

**Issue by Xenphor** [ata4/angrylion-rdp-plus#82]
After testing the new vsync and exclusive full screen options I noticed that they don't save to the ini file in the GFX directory using Project 64. I have to enable them every time I open Project 64. Using Project 64 v2.4.0-954-gbf26945

**Comment by RokkumanX** [comment]
This issue is now resolved, both Vsync and Exclusive Fullscreen is working and saving correctly here.
