### ISSUE TITLE
Increasing color depth

### ISSUE THREAD

**Issue by jonathan25** [ata4/angrylion-rdp-plus#86]
As I understand the N64 handles everything in RGBA8888 (32-bit) but it is limited by its 16-bit color frame buffer, and for this reason dithering is needed. I was wondering, is it possible render in 32-bit color? If so, how much work is needed to add this as an option?

**Comment by CrashOveride95** [comment]
I don't think that's the focus of this plugin

**Comment by gamemasterplc** [comment]
Also a few games do output in 32-bit color including doom 64.

**Comment by theboy181** [comment]
This option would be neat, if possible.

**Comment by jonathan25** [comment]
@CrashOveride95 just to be clear, I'm not asking to add this as an option because, well yes, the focus of this plugin is to be as accurate possible. I'm just wondering if it's possible to force games to output 32-bit color.

**Comment by ata4** [comment]
The problem is that RGBA8888 requires more space in RAM than RGBA5551, for example. When the format is forced to be RGBA8888, the memory layout no longer matches and the RDP overwrites program code or other things.

**Comment by jonathan25** [comment]
I see, then it's not possible unless a hacky way is implemented, like having a 16-bit framebuffer in memory but displaying/rendering a 32-bit one. But then again this is out of the scope of this plugin and probably would take more processing power.
