### ISSUE TITLE
slow performance despite CPU not at full load

### ISSUE THREAD

**Issue by belegdol** [ata4/angrylion-rdp-plus#87]
Hello,

it appears that the plugin is having hard time rendering at full speed on Ryzen 5 2600 despite the cpu being quite far from being at full load. I have compiled the git master of this plugin and tested it with mupen64plus. With Goldeneye 007 (beginning of dam level) and Conker's Bad Fur Day (menu in the bar) the performance is very slow and sound is choppy. The CPU is only at 50 % or so load though:
![angrylion-rdp-plus](https://user-images.githubusercontent.com/1208329/60769833-ce875f80-a0d4-11e9-9142-18293e85d630.png)
For comparison purposes I tried MAME with frame limiter disabled, and the cores do go up to 100% load one after another.
This is happening on linux (Fedora 30) with mupen64plus and cxd4 RSP plugin. Is this an expected behaviour? I am happy to provide more detailed test data if necessary.

**Comment by LegendOfDragoon** [comment]
> Is this an expected behaviour?

What's happening is that you're playing resource intensive games that have CPU/RSP bottlenecks. This plugin only can run RDP in separate threads, so CPU and RSP are still ran in 1 single thread. I would have suggested using Project64 since it's faster than Mupen64Plus, but I see that you're using Linux.

**Comment by belegdol** [comment]
@LegendOfDragoon thank you for the explanation! I am still a bit confused though: if CPU/RSP are running on a single thread and this is what is causing the slowness, shouldn't at least one of the 12 threads be hitting 100%? This is how the cpu usage looks with MAME:
![mame](https://user-images.githubusercontent.com/1208329/60771735-46ad4f80-a0ec-11e9-9bc0-ac0847aeca4d.png)

**Comment by LegendOfDragoon** [comment]
>shouldn't at least one of the 12 threads be hitting 100%?

Not sure if there's possibly additional problems in your case. One good way to test, is to try a game that is RDP intensive and not CPU or RSP intensive. Yoshi's Story is a good example. On Project64, I got ~95% total CPU utilization when I uncapped the frame limiter in Project64 in Yoshi's Story. However that was months ago, and I haven't tested the latest build. I also only have 4 cores and 4 threads on my PC.

**Comment by belegdol** [comment]
With Yoshi's story I am able to get full speed. Strangely enough the CPU usage does not go up even with --nospeedlimit:
![yoshisstory](https://user-images.githubusercontent.com/1208329/60786105-88beab80-a155-11e9-9cc4-7dcf0c46143d.png)
When I switched video plugin to glide64mk2, the CPU usage does go up to full:
![glideframelimitoff](https://user-images.githubusercontent.com/1208329/60786129-9e33d580-a155-11e9-9651-0361c0e47471.png)
Is there a way to display the VI/s resp. FPS with angrylion-plus and mupen64plus?

**Comment by LegendOfDragoon** [comment]
>Strangely enough the CPU usage does not go up even with --nospeedlimit

That is strange. I am guessing that vsync is enabled somehow. I'm not sure if Mupen64plus supports displaying the VI/s.

**Comment by belegdol** [comment]
I tried testing using Windows and PJ64 but with released versions (2.3.2 and r7) the performance is quite substantially lower than on Linux. I will see how compiling from git master goes.

**Comment by ata4** [comment]
With the latest Git, I get a peak usage of around 86% with GoldenEye and Project 64 using the same CPU under extreme conditions (screen filled with smoke):
![goldeneye](https://user-images.githubusercontent.com/1200105/60836233-7bd9a080-a1c5-11e9-9381-0b6ca2af7758.png)

Normal gameplay is pretty fluid, though. Especially with the VI filter disabled.

**Comment by theboy181** [comment]
Did you uncheck frame limit? Also there is a JAP game that will cook your CPU. https://en.m.wikipedia.org/wiki/Zoor:_Majū_Tsukai_Densetsu

**Comment by LegendOfDragoon** [comment]
>Did you uncheck frame limit?

You just reminded me. Maybe he had Sync using audio enabled in PJ64.

> I will see how compiling from git master goes.

Yeah try the latest build and also disable Sync using audio in Project64. I'd love to see the results of how much CPU is being used in Yoshi Story in Project64 with frame limiter disabled.

**Comment by belegdol** [comment]
I managed to compile a 32bit build of both pj64 and the plugin (x64 build of the plugin fails horribly in VS2019). I am getting similar results: one core at full load in goldeneye with pretty fluid gameplay:
![pj64_goldeneye](https://user-images.githubusercontent.com/1208329/60840293-72553600-a1cf-11e9-89d9-79d0148f7c3c.png)
With conkers the initial menu where conker stumbles into a bar is choppy but then things get faster, still one core is at full load:
![pj64](https://user-images.githubusercontent.com/1208329/60840360-9ca6f380-a1cf-11e9-95e5-292510ba061a.png)
So it seems like it might have been an issue with the gnome-system-monitor after all, apart from pj64 being faster than mupen64.

**Comment by belegdol** [comment]
> Yeah try the latest build and also disable Sync using audio in Project64. I'd love to see the results of how much CPU is being used in Yoshi Story in Project64 with frame limiter disabled.

Oddly enough frame limiter seems to do nothing despite the disabled vsync:
![yoshi](https://user-images.githubusercontent.com/1208329/60842081-99156b80-a1d3-11e9-8d53-c5948ba0f6c0.png)
Only once the window is minimized the emulation uses full CPU power available:
![yoshiminimized](https://user-images.githubusercontent.com/1208329/60842112-a894b480-a1d3-11e9-9163-c2e8a61d0ef1.png)

**Comment by ata4** [comment]
Interesting, I didn't know that the utilization rises when the window is hidden. Maybe there is actually a problem with the OpenGL output. I'll look into that soon...

**Comment by belegdol** [comment]
Sorry if it was not clear: utilisation goes up because I can't seem to be able to get rid of vsync with the window visible. With the window minimised you can hear the emulation going beyond 100% speed.

**Comment by belegdol** [comment]
I believe I was able to finally find the root cause of below-playable framerates in Conker's BFD and Goldeneye with mupen64plus: it looks like it was rsp-cxd4, not angrylion-rdp-plus.
Using project64's ability to switch plugins on the fly, I was able to verify this on a particular place in Conker. PJ64's RSP was delivering 60 fps while rsp-cxd4 was diving to half of that.
Looks like Ryzen 5 2600 is not enough for both of these plugins in heavy games.

**Comment by LegendOfDragoon** [comment]
>Is it possible that RSP plugin is making RDP slower?

What's happening is that since the RSP cannot run in parallel with RDP under most N64 emulators, a slower RSP means that the RDP has less time since the RSP typically runs before the RDP.

> I can't seem to be able to get rid of vsync with the window visible

Have you tried editing driver settings for your GPU?

**Comment by belegdol** [comment]
> > Is it possible that RSP plugin is making RDP slower?
> 
> What's happening is that since the RSP cannot run in parallel with RDP under most N64 emulators, a slower RSP means that the RDP has less time since the RSP typically runs before the RDP.
> 
This does make sense... Having said that, with perf under linux RSP does not appear to be using any significant CPU time.
> > I can't seem to be able to get rid of vsync with the window visible
> 
> Have you tried editing driver settings for your GPU?
I did try changing vsync in nvidia control panel from app controlled to force off, it did not seem to do anything.

**Comment by belegdol** [comment]
I just tried disabling vsync in nvidia CP again, turns out you need to disable vsync AND restart PJ64 after doing that. This allowed me to get some proper numbers:
- conker with pj64 rsp: approx. 75 VI/s
- conker with cxd4 rsp: approx. 45 VI/s
- yoshi's story with pj64 rsp: approx. 130 VI/s
- yoshi's story with cxd4 rsp: approx. 120 VI/s
It looks like this issue can finally be closed, with the conclusion that PJ64's RSP is considerably faster than cxd4.

**Comment by zenseii** [comment]
What you are saying is true, however I think a more precise way of putting it is that cd4 rsp is more accurate and therefore requires more in terms of cpu power. There are examples where you see the difference between the native pj64 rsp and cd4, though I don't remember any. This is the same reason why angrylion is more taxing than for example gliden64 (without any enhancement options enabled ofc). This is the trade-off but hopefully angrylion rdp plus will become optimized enough for multithreading that it can run smoothly without having to buy higher end components.

Anyways, your finding about vsync helps, since disabling it gives a speed boost too so thanks.

**Comment by Jj0YzL5nvJ** [comment]
Benchmark: https://imgur.com/a/mJ1UZ1u

In previous versions, angrylion-plus always used between 85% to 100% of CPU on my PC. But the performance was terrible, now it's much better. Now it is difficult to raise the CPU above of 60%.
The only way I can force the use of 100% of the CPU is compiling with _-j6_... maybe angrylion-plus does not benefit from the unganged mode in AMD processors.

**Comment by belegdol** [comment]
> What you are saying is true, however I think a more precise way of putting it is that cxd4 rsp is more accurate and therefore requires more in terms of cpu power. There are examples where you see the difference between the native pj64 rsp and cxd4, though I don't remember any.

Fair point - I should have mentioned it. Unfortunately, given the limited CPU power I have to decide where to sacrifice the accuracy, and I prefer the old blurry look of software renderer to sharp polygons with low-res textures.
I need to check if z64 RSP is any good, sadly the mupen64plus RSP appears to be HLE only and thus incompatible with angrylion.

**Comment by LegendOfDragoon** [comment]
> I think a more precise way of putting it is that cxd4 rsp is more accurate and therefore requires more in terms of cpu power.

The main difference in performance is due to the fact that cxd4's uses an interpreter, while PJ64's RSP has a recompiler.

>sadly the mupen64plus RSP appears to be incompatible with angrylion.

The reason mupen's RSP doesn't work is because it's HLE only. You need an LLE RSP to run Angrylion.

**Comment by ata4** [comment]
> I just tried disabling vsync in nvidia CP again, turns out you need to disable vsync AND restart PJ64 after doing that.

Thanks for pointing that out, `wglSwapIntervalEXT` was actually only set to 1 when vsync is enabled, but not back to 0 when it's disabled. Will fix that.

> (x64 build of the plugin fails horribly in VS2019)

Also thanks for that one, forgot to exclude some files from the compilation for x64. I'll also add some checks to prevent build errors even if that setting is incorrect for whatever reason.

**Comment by Jj0YzL5nvJ** [comment]
Issue potentially fixed by #115 (`--set Video-Angrylion-Plus[BusyLoop]=True`)

**Comment by belegdol** [comment]
I have a Ryzen 5600x now. With busyloop enabled, Conker BFD got from playable at almost full speed to unplayably choppy.

**Comment by Jj0YzL5nvJ** [comment]
Certainly CBFD is one of those games that my CPU can't run smoothly. My CPU is simply too old (`AMD Phenom II X6 1090T`).

```
GALLIUM_HUD="cpu+GPU-load+fps,cpu0+cpu1+cpu2+cpu3+cpu4+cpu5,.drequested-VRAM+VRAM-usage+mapped-VRAM+GTT-usage+mapped-GTT,buffer-wait-time" m64pp --windowed --resolution 960x720 --gfx mupen64plus-video-angrylion-plus.so --rsp mupen64plus-rsp-parallel.so --set Video-Angrylion-Plus[Parallel]=True --set Video-Angrylion-Plus[NumWorkers]=0 --set Video-Angrylion-Plus[BusyLoop]=True --set Video-Angrylion-Plus[ViMode]=0 --set Video-Angrylion-Plus[ViInterpolation]=2 --set Video-Angrylion-Plus[ViWidescreen]=False --set Video-Angrylion-Plus[ViHideOverscan]=False --set Video-Angrylion-Plus[ViIntegerScaling]=False --set Video-Angrylion-Plus[DpCompat]=2 CBFD.z64
```
<img src="https://i.imgur.com/HkeXgNM.png" alt="" class="">

Other games work acceptably even with 4 threads and recording software...
https://imgur.com/a/oadb6hV
https://imgur.com/a/FVzNXgO

> Multithreading needs to be adjusted in some cases, that's why it keeps getting better.
> Some CPUs can benefit more than others. Too many multithreading could potentially impair performance in some games by spending more time syncing threads.
> Some newer Intel processors don't have hyperthreading and other older processors work better without it... etc.
