### ISSUE TITLE
Plugin does not load in mupen64plus anymore

### ISSUE THREAD

**Issue by Pixelnarium** [ata4/angrylion-rdp-plus#88]
Since https://github.com/ata4/angrylion-rdp-plus/commit/feb4d2689fca09e67367de1576c30611fec21a83 from yesterday the plugin does not load in mupen anymore. The m64p GUI (before the GlideN64 GUI change) also can't read any of the settings. Trying it with the CLI mupen it gave me this error:

`UI-Console Error: dlopen('./mupen64plus-video-angrylion-plus.so') failed: ./mupen64plus-video-angrylion-plus.so: undefined symbol: _ptrc_glCompileShader`

It works when I compile it with -DGLES=ON. At least in the CLI application. 

ArchLinux btw.

**Comment by Jj0YzL5nvJ** [comment]
Same thing on `Xubuntu 16.04.6 LTS AMD64`.

**Comment by ata4** [comment]
Yeah, I see what's the issue here... I'll fix the CMakeLists script soon.
