### ISSUE TITLE
Doesn't work with mupen64plus on Arch Linux

### ISSUE THREAD

**Issue by jhlkek** [ata4/angrylion-rdp-plus#96]
I am able to build this program successfully with this AUR package: https://aur.archlinux.org/packages/mupen64plus-video-angrylion-plus-git/ , but when I try to run it with mupen64plus I get the following error:

UI-Console Error: dlopen('/usr/lib64/mupen64plus/mupen64plus-video-angrylion-plus.so') failed: /usr/lib64/mupen64plus/mupen64plus-video-angrylion-plus.so: undefined symbol: pthread_create
UI-Console Error: Specified Video plugin not found: mupen64plus-video-angrylion-plus
Core Status: Rom closed.

I'm using mupen64plus 2.5.0.

**Comment by jonathan25** [comment]
I had the same problem, it seems that it was a problem with mupen64plus because I just tried with the newest build and it worked perfectly.
