### ISSUE TITLE
Nemu64 support

### ISSUE THREAD

**Issue by jtl3d** [ata4/angrylion-rdp-plus#99]
Can this work with Nemu64?

**Comment by CrashOveride95** [comment]
Why would you need Nemu64?

**Comment by jtl3d** [comment]
That's where I do all my debugging. I haven't tried new PJ64 builds - how does that debugger stack up?

**Comment by CrashOveride95** [comment]
PJ64 Nightly's debugger is MUCH better, I highly suggest just getting that. Nemu64 debugging is ancient and has gone the way of the dodo
